import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import type { SchemaSnapshot } from "../types";

const fixturePath = path.resolve(__dirname, "../fixtures/keycloak.snapshot.json");

function loadFixture(): SchemaSnapshot {
  return JSON.parse(readFileSync(fixturePath, "utf8")) as SchemaSnapshot;
}

describe("fixture conformance", () => {
  // This fixture is generated by the REAL Rust serializer. Its job is to fail
  // when the Rust model changes shape, so the hand-maintained types.ts cannot
  // drift silently.

  it("has the shape types.ts declares", () => {
    const snapshot = loadFixture();
    expect(snapshot.formatVersion).toBe(1);
    expect(Array.isArray(snapshot.tables)).toBe(true);
    expect(snapshot.tables.length).toBeGreaterThan(0);
    expect(typeof snapshot.project.databaseType).toBe("string");
    expect(Array.isArray(snapshot.project.schemas)).toBe(true);
  });

  it("uses camelCase for snapshot-owned fields", () => {
    const raw = JSON.parse(readFileSync(fixturePath, "utf8")) as Record<string, unknown>;
    expect(raw).toHaveProperty("formatVersion");
    expect(raw).not.toHaveProperty("format_version");

    const table = (raw.tables as Record<string, unknown>[])[0];
    expect(table).toHaveProperty("noteSource");
    expect(table).toHaveProperty("columnNotes");
    expect(table).toHaveProperty("foreignKeys");
    expect(table).not.toHaveProperty("note_source");
  });

  it("keeps snake_case on columns, which come from crate::types", () => {
    const snapshot = loadFixture();
    const withColumns = snapshot.tables.find((table) => table.columns.length > 0);
    expect(withColumns, "fixture must contain at least one table with columns").toBeDefined();
    const column = withColumns!.columns[0] as unknown as Record<string, unknown>;
    expect(column).toHaveProperty("data_type");
    expect(column).toHaveProperty("is_nullable");
    expect(column).not.toHaveProperty("dataType");
  });

  it("carries an annotated note, a group and an orphan warning", () => {
    const snapshot = loadFixture();

    const annotated = snapshot.tables.find((table) => table.noteSource === "LOCAL");
    expect(annotated, "fixture must include a LOCAL-sourced note").toBeDefined();
    expect(annotated!.note).toBeTruthy();

    expect(snapshot.groups.length).toBeGreaterThan(0);
    expect(typeof snapshot.groups[0].hue).toBe("number");

    const orphan = snapshot.warnings.find((warning) => warning.kind === "orphanedNotes");
    expect(orphan, "fixture must include an orphanedNotes warning").toBeDefined();
  });

  it("every warning discriminant is one types.ts knows", () => {
    const known = new Set(["tableSkipped", "noForeignKeyMetadata", "commentsUnsupported", "orphanedNotes", "dbmlOmitted"]);
    for (const warning of loadFixture().warnings) {
      expect(known.has(warning.kind), `unknown warning kind: ${warning.kind}`).toBe(true);
    }
  });

  it("column objects carry every field types.ts declares as required", () => {
    // types.ts marks these required because Rust has no skip_serializing_if.
    // If Rust ever adds one, the key vanishes and this fails — which is the
    // whole point of validating against real output rather than a literal.
    const snapshot = loadFixture();
    const table = snapshot.tables.find((candidate) => candidate.columns.length > 0);
    expect(table, "fixture needs a table with columns").toBeDefined();
    const column = table!.columns[0] as unknown as Record<string, unknown>;
    for (const key of ["name", "data_type", "is_nullable", "column_default", "is_primary_key", "extra", "comment", "numeric_precision", "numeric_scale", "character_maximum_length"]) {
      expect(Object.hasOwn(column, key), `column must always carry ${key}`).toBe(true);
    }
  });

  it("index objects carry every field types.ts declares as required", () => {
    const snapshot = loadFixture();
    const table = snapshot.tables.find((candidate) => candidate.indexes.length > 0);
    expect(table, "fixture needs a table with indexes").toBeDefined();
    const index = table!.indexes[0] as unknown as Record<string, unknown>;
    for (const key of ["name", "columns", "is_unique", "is_primary", "filter", "index_type", "included_columns", "comment"]) {
      expect(Object.hasOwn(index, key), `index must always carry ${key}`).toBe(true);
    }
  });
});
